"use client";
import { useMemo, useState, type FormEvent } from "react";
import Link from "next/link";
import { Plus, X } from "lucide-react";
import { Button, Card, StatusChip } from "@kcl/ui";
import { addChildToFamily, addGuardianToFamily, updateRegistrationDocument, useAuthAccess, useMinistryCollection } from "@kcl/firebase";
import type { Child, Guardian, Household, MinistryGroup } from "@kcl/types";
import { childRegistrationSchema, guardianSchema } from "@kcl/validation";

type HouseholdDetail = Household & { address?: string; preferredContactMethod?: string; emergencyContactSummary?: { name?: string; phone?: string } };
const newGuardian = () => ({ fullName: "", phone: "", email: "", relationship: "Parent", authorizedPickup: true, emergencyContact: false });
const newChild = () => ({ firstName: "", lastName: "", preferredName: "", birthdate: "", ministryGroupId: "", allergies: "", medicalNotes: "", assistanceNotes: "" });

export function FamilyRecord({ family, onClose }: { family: HouseholdDetail; onClose(): void }) {
  const { member } = useAuthAccess(); const guardianData = useMinistryCollection<Guardian>("guardians"); const childData = useMinistryCollection<Child>("children"); const groupData = useMinistryCollection<MinistryGroup>("ministryGroups");
  const guardians = guardianData.data.filter((item) => item.householdId === family.id && item.active); const children = childData.data.filter((item) => item.householdId === family.id && item.active); const groups = useMemo(() => groupData.data.filter((item) => item.active).sort((a, b) => a.displayOrder - b.displayOrder), [groupData.data]);
  const [tab, setTab] = useState("overview"); const [adding, setAdding] = useState(false); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(""); const [error, setError] = useState("");
  const [overview, setOverview] = useState({ householdName: family.householdName, address: family.address || "", preferredContactMethod: family.preferredContactMethod || "PHONE", emergencyName: family.emergencyContactSummary?.name || "", emergencyPhone: family.emergencyContactSummary?.phone || "" });
  const [guardian, setGuardian] = useState(newGuardian); const [child, setChild] = useState(newChild);
  const run = async (action: () => Promise<unknown>, success: string) => { setBusy(true); setError(""); try { await action(); setNotice(success); setAdding(false); } catch (value) { setError(value instanceof Error ? value.message : "The record could not be saved."); } finally { setBusy(false); } };
  async function saveOverview(event: FormEvent) { event.preventDefault(); if (!member) return; if (overview.householdName.trim().length < 2 || overview.emergencyName.trim().length < 2 || overview.emergencyPhone.trim().length < 7) return setError("Complete the household and emergency contact details."); await run(() => updateRegistrationDocument(member, "households", family.id, { householdName: overview.householdName.trim(), normalizedHouseholdName: overview.householdName.trim().toLowerCase(), address: overview.address.trim(), preferredContactMethod: overview.preferredContactMethod, emergencyContactSummary: { name: overview.emergencyName.trim(), phone: overview.emergencyPhone.trim() } }, "Ordinary registration details corrected with guardian"), "Household details updated."); }
  async function saveGuardian(event: FormEvent) { event.preventDefault(); if (!member) return; const parsed = guardianSchema.safeParse(guardian); if (!parsed.success) return setError(parsed.error.issues[0]?.message || "Complete the guardian details."); await run(() => addGuardianToFamily(member, family.id, children.map((item) => item.id), parsed.data), "Guardian added and pickup access linked safely."); setGuardian(newGuardian()); }
  async function saveChild(event: FormEvent) { event.preventDefault(); if (!member) return; const parsed = childRegistrationSchema.safeParse(child); if (!parsed.success) return setError(parsed.error.issues[0]?.message || "Complete the child details."); await run(() => addChildToFamily(member, family.id, guardians.map((item) => item.id), guardians.filter((item) => item.authorizedPickup).map((item) => item.id), parsed.data), "Child and care information added."); setChild(newChild()); }
  async function editGuardian(item: Guardian) { if (!member) return; const phone = window.prompt(`Phone for ${item.fullName}`, item.phone); if (phone == null) return; const email = window.prompt(`Email for ${item.fullName}`, item.email || ""); if (email == null) return; await run(() => updateRegistrationDocument(member, "guardians", item.id, { phone, normalizedPhone: phone.replace(/\D/g, ""), email, normalizedEmail: email.toLowerCase() }, "Guardian contact details corrected with family"), "Guardian contact updated."); }
  async function editCare(item: Child) { if (!member) return; const allergies = window.prompt(`Allergies for ${item.preferredName || item.firstName}`, item.allergies || ""); if (allergies == null) return; const medicalNotes = window.prompt("Medical information", item.medicalNotes || ""); if (medicalNotes == null) return; const assistanceNotes = window.prompt("Assistance needs", item.assistanceNotes || ""); if (assistanceNotes == null) return; await run(() => updateRegistrationDocument(member, "children", item.id, { allergies: allergies.trim(), medicalNotes: medicalNotes.trim(), assistanceNotes: assistanceNotes.trim() }, "Child safety information reviewed with guardian"), "Child care information updated."); }
  return <Card className="section family-record"><div className="section-head"><div><small className="muted">Family registration record</small><h2>{family.householdName}</h2></div><Button variant="ghost" aria-label="Close family record" onClick={onClose}><X /></Button></div>{notice && <div className="form-success" role="status">{notice}</div>}{error && <div className="form-error" role="alert">{error}</div>}<div className="record-tabs" role="tablist">{["overview", "guardians", "children", "pass"].map((item) => <button key={item} role="tab" aria-selected={tab === item} className={tab === item ? "active" : ""} onClick={() => { setTab(item); setAdding(false); }}>{item === "pass" ? "Family Pass" : item[0].toUpperCase() + item.slice(1)}</button>)}</div>
    {tab === "overview" && <form onSubmit={(event) => void saveOverview(event)}><div className="split"><Field label="Household name" value={overview.householdName} onChange={(value) => setOverview({ ...overview, householdName: value })} /><label className="field"><span>Preferred contact</span><select value={overview.preferredContactMethod} onChange={(e) => setOverview({ ...overview, preferredContactMethod: e.target.value })}><option value="PHONE">Phone</option><option value="EMAIL">Email</option><option value="IN_PERSON">In person</option></select></label></div><Field label="Address" value={overview.address} onChange={(value) => setOverview({ ...overview, address: value })} textarea /><div className="split"><Field label="Emergency contact" value={overview.emergencyName} onChange={(value) => setOverview({ ...overview, emergencyName: value })} /><Field label="Emergency phone" value={overview.emergencyPhone} onChange={(value) => setOverview({ ...overview, emergencyPhone: value })} /></div><Button disabled={busy}>{busy ? "Saving…" : "Save ordinary corrections"}</Button><p className="help">Household deactivation and disputed changes must be escalated to a Ministry Lead.</p></form>}
    {tab === "guardians" && <>{guardians.map((item) => <article className="family-row" key={item.id}><div><h3>{item.fullName}</h3><p>{item.relationship} · {item.phone}{item.email ? ` · ${item.email}` : ""}</p></div><div className="row-side"><StatusChip tone={item.authorizedPickup ? "success" : "neutral"}>{item.authorizedPickup ? "Pickup authorized" : "Not authorized"}</StatusChip><Button variant="ghost" onClick={() => void editGuardian(item)}>Edit contact</Button></div></article>)}{adding ? <form className="sub-card" onSubmit={(event) => void saveGuardian(event)}><h3>Add guardian</h3><div className="split"><Field label="Full name" value={guardian.fullName} onChange={(value) => setGuardian({ ...guardian, fullName: value })} /><Field label="Phone" value={guardian.phone} onChange={(value) => setGuardian({ ...guardian, phone: value })} /><Field label="Email (optional)" value={guardian.email} onChange={(value) => setGuardian({ ...guardian, email: value })} /><Field label="Relationship" value={guardian.relationship} onChange={(value) => setGuardian({ ...guardian, relationship: value })} /></div><label className="check"><input type="checkbox" checked={guardian.authorizedPickup} onChange={(e) => setGuardian({ ...guardian, authorizedPickup: e.target.checked })} />Authorized for pickup</label><Button disabled={busy}>Add guardian</Button></form> : <Button variant="ghost" onClick={() => setAdding(true)}><Plus size={17} /> Add guardian</Button>}<p className="help">Revoking established pickup authorization is escalated to a Ministry Lead.</p></>}
    {tab === "children" && <>{children.map((item) => <article className="family-row" key={item.id}><div><h3>{item.preferredName || item.firstName} {item.lastName}</h3><p>{item.birthdate} · {groups.find((group) => group.id === item.ministryGroupId)?.name || "Group not set"}</p></div><div className="row-side">{(item.allergies || item.medicalNotes || item.assistanceNotes) && <StatusChip tone="danger">Care details</StatusChip>}<Button variant="ghost" onClick={() => void editCare(item)}>Update care info</Button></div></article>)}{adding ? <form className="sub-card" onSubmit={(event) => void saveChild(event)}><h3>Add child</h3><div className="split"><Field label="First name" value={child.firstName} onChange={(value) => setChild({ ...child, firstName: value })} /><Field label="Last name" value={child.lastName} onChange={(value) => setChild({ ...child, lastName: value })} /><Field label="Preferred name" value={child.preferredName} onChange={(value) => setChild({ ...child, preferredName: value })} /><Field label="Birthdate" type="date" value={child.birthdate} onChange={(value) => setChild({ ...child, birthdate: value })} /></div><label className="field"><span>Ministry group</span><select value={child.ministryGroupId} onChange={(e) => setChild({ ...child, ministryGroupId: e.target.value })}><option value="">Choose group</option>{groups.map((group) => <option key={group.id} value={group.id}>{group.name}</option>)}</select></label><Field label="Allergies" value={child.allergies} onChange={(value) => setChild({ ...child, allergies: value })} textarea /><Field label="Medical information" value={child.medicalNotes} onChange={(value) => setChild({ ...child, medicalNotes: value })} textarea /><Field label="Assistance needs" value={child.assistanceNotes} onChange={(value) => setChild({ ...child, assistanceNotes: value })} textarea /><Button disabled={busy}>Add child</Button></form> : <Button variant="ghost" onClick={() => setAdding(true)}><Plus size={17} /> Add child</Button>}</>}
    {tab === "pass" && <div className="empty-state"><StatusChip tone={family.passStatus === "ACTIVE" ? "success" : "warning"}>{family.passStatus || "No pass"}</StatusChip><h3>Family Pass controls</h3><p>Print, download, copy, reprint, or perform a verified lost/damaged replacement.</p><Link className="button button-primary" href={`/passes/?family=${family.id}`}>Open Family Pass</Link></div>}
  </Card>;
}

function Field({ label, value, onChange, textarea = false, type = "text" }: { label: string; value: string; onChange(value: string): void; textarea?: boolean; type?: string }) { return <label className="field"><span>{label}</span>{textarea ? <textarea value={value} onChange={(e) => onChange(e.target.value)} /> : <input type={type} value={value} onChange={(e) => onChange(e.target.value)} />}</label>; }
