"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
import { EmptyState, StatusChip } from "@kcl/ui";
import { useMinistryCollection } from "@kcl/firebase";
import type { FamilyPassSecret, Household } from "@kcl/types";

export function FamilySearch({ compact = false, onSelect }: { compact?: boolean; onSelect?(family: Household): void }) {
  const { data, loading, error } = useMinistryCollection<Household>("households"); const passes = useMinistryCollection<FamilyPassSecret>("familyPassSecrets"); const [query, setQuery] = useState("");
  const results = useMemo(() => { const term = query.trim().toLocaleLowerCase(); const digits = term.replace(/\D/g, ""); const key = term.toUpperCase().replace(/[^A-Z0-9]/g, ""); if (!term) return compact ? data.slice(0, 5) : data; return data.filter((family) => { const terms = [family.householdName, family.primaryGuardianName, ...(Array.isArray((family as Household & { normalizedSearchTerms?: string[] }).normalizedSearchTerms) ? (family as Household & { normalizedSearchTerms?: string[] }).normalizedSearchTerms! : [])]; const pass = passes.data.find((item) => item.id === family.id || item.householdId === family.id); return terms.some((value) => value?.toLocaleLowerCase().includes(term) || (digits.length >= 4 && value?.replace(/\D/g, "").endsWith(digits))) || Boolean(key.startsWith("KCL") && pass?.formattedDisplayKey.replace(/[^A-Z0-9]/g, "") === key); }); }, [data, passes.data, query, compact]);
  return <><div className="search-bar"><label className="field" style={{ margin: 0, flex: 1 }}><span className="help">Search before registering to prevent duplicates</span><input className="search-input" aria-label="Search families" placeholder="Household, guardian, child, phone suffix, or Family Key" value={query} onChange={(e) => setQuery(e.target.value)} /></label></div>{loading ? <div className="loading"><div><div className="spinner" />Loading families…</div></div> : error ? <div className="alert alert-error">Families could not be loaded. Check your connection and access.</div> : results.length ? <div className="family-list">{results.map((family) => <article className="family-row" key={family.id}><div><h3>{family.householdName}</h3><p>{family.primaryGuardianName || "Primary guardian not recorded"} · {family.childIds?.length || 0} {(family.childIds?.length || 0) === 1 ? "child" : "children"}</p></div><div className="row-side"><StatusChip tone={family.passStatus === "ACTIVE" ? "success" : "warning"}>{family.passStatus || "No pass"}</StatusChip>{onSelect ? <button className="button button-ghost" onClick={() => onSelect(family)}>Open record</button> : <Link className="button button-ghost" href={`/passes/?family=${family.id}`}>View pass</Link>}</div></article>)}</div> : <EmptyState title={query ? "No matching family" : "No families registered yet"} description={query ? "Check the spelling or try a guardian, child, phone suffix, or exact Family Key." : "Start with a careful duplicate search, then register the first family."} action={!query && <Link className="button button-primary" href="/register/">Register a family</Link>} />}</>;
}
