"use client";
import { useEffect, useState, type FormEvent } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { BrandMark, Button } from "@kcl/ui";
import { resetPassword, signInEmail, signInGoogle, useAuthAccess } from "@kcl/firebase";

function message(error: unknown) { const code = typeof error === "object" && error && "code" in error ? String(error.code) : ""; if (code.includes("invalid-credential")) return "That email or password was not accepted."; if (code.includes("popup-closed")) return "Google sign-in was cancelled."; if (code.includes("too-many")) return "Too many attempts. Please wait, then try again."; return "Sign-in is unavailable right now. Check your connection and try again."; }
export default function SignInPage() {
  const { state } = useAuthAccess(); const router = useRouter(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  useEffect(() => { if (state === "ACTIVE") router.replace("/home/"); else if (!["LOADING", "SIGNED_OUT"].includes(state)) router.replace("/access/"); }, [state, router]);
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { await signInEmail(email, password); } catch (value) { setError(message(value)); } finally { setBusy(false); } }
  async function google() { setBusy(true); setError(""); try { await signInGoogle(); } catch (value) { setError(message(value)); } finally { setBusy(false); } }
  async function reset() { if (!email) return setError("Enter your email first, then choose Reset password."); setBusy(true); try { await resetPassword(email); setNotice("Password reset instructions were sent if that account exists."); } catch (value) { setError(message(value)); } finally { setBusy(false); } }
  return <main className="auth-page"><section className="auth-story"><BrandMark /><div><span className="auth-tag">Admin Volunteer</span><h1>A warm welcome starts with one careful conversation.</h1><p>Register a family once, keep their information current, and give them a pass they can use every Sunday.</p></div><small className="muted">No family phone, email, or account required.</small></section><section className="auth-panel"><form className="auth-form" onSubmit={submit}><BrandMark /><h2>Welcome back</h2><p>Sign in with your approved registration-team account.</p>{error && <div className="form-error" role="alert">{error}</div>}{notice && <div className="form-success" role="status">{notice}</div>}<div className="field"><label htmlFor="email">Email</label><input id="email" type="email" autoComplete="email" required value={email} onChange={(event) => setEmail(event.target.value)} /></div><div className="field"><label htmlFor="password">Password</label><input id="password" type="password" autoComplete="current-password" required value={password} onChange={(event) => setPassword(event.target.value)} /></div><Button disabled={busy} type="submit">{busy ? "Signing in…" : "Sign in"}</Button><button className="text-button" type="button" onClick={() => void reset()} disabled={busy}>Reset password</button><div className="divider">or</div><Button variant="secondary" type="button" onClick={() => void google()} disabled={busy}>Continue with Google</Button><p className="auth-switch">New team member? <Link href="/create-account/">Create an account and request access</Link></p></form></section></main>;
}
